### ISSUE TITLE
nflgame-update-player not working

### ISSUE THREAD

**Issue by itguypw** [BurntSushi/nfldb#100] opened 2015-09-13 22:42 UTC
I noticed that some players were missing data. I tried running the nflgame-update-player operation.  I got issues with the following message: "python/lib/python2.7/site-packages/beautifulsoup4-4.4.0-py2.7.egg/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently."
Am I missing something?

**Comment by BurntSushi** [comment] 2015-09-13 22:47
Please paste the **full output** of running the command. The part you've shown here is a warning message that is OK.

**Comment by itguypw** [comment] 2015-09-13 22:55
I have posted the entire output. I am running nfldb, which is not updating the player data either.. I have 617 players with player_id and gsis_name but everything else is null. 

 [~/python/bin]# nflgame-update-players
Loading games for REG 2015 week 1
Finding (profile id -> gsis id) mapping for players...
93/93 complete. (100.00%)
Done!
Downloading team rosters...
/home2/aintlike/python/lib/python2.7/site-packages/beautifulsoup4-4.4.0-py2.7.egg/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

Traceback (most recent call last):
  File "/home2/aintlike/python/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/home2/aintlike/python/lib/python2.7/site-packages/nflgame/update_players.py", line 398, in run
    for i, (team, soup) in enumerate(pool.imap(fetch, teams), 1):
  File "/home2/aintlike/python/Python-2.7.2/Lib/multiprocessing/pool.py", line 620, in next
    raise value
HTMLParser.HTMLParseError: bad end tag: u"</sc'+'ript>", at line 2323, column 94
/home2/aintlike/python/lib/python2.7/site-packages/beautifulsoup4-4.4.0-py2.7.egg/bs4/builder/_htmlparser.py:167: RuntimeWarning: Python's built-in HTMLParser cannot parse the given document. This is not a bug in Beautiful Soup. The best solution is to install an external parser (lxml or html5lib), and use Beautiful Soup with that parser. See http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser for help.

**Comment by BurntSushi** [comment] 2015-09-13 23:03
It's working fine for me over here. This might be a genuine bug where switching out the parser used in beautifulsoup might be a good idea.

I'm going to call this a dupe of: https://github.com/BurntSushi/nflgame/issues/137

**Closed by BurntSushi** 2015-09-13 23:03 UTC
